### ISSUE TITLE
Getting results back into revit

### ISSUE THREAD

**Issue by Lexiko** [ladybug-analysis-tools/ladybug-dynamo#10]
I am able to run the analysis on surfaces selected from revit. I'm stuck with getting results back into revit. The "FaceAnalysisbyViewPoints and results" node only returns one surface. Am I missing something?

**Comment by mostaphaRoudsari** [comment]
Hi @Lexiko! Thank you for posting the issue and also posting it to [the forum](http://dynamobim.org/forums/topic/face-analysis-display-by-view-face-points-and-values-node-bug/). Looks like there is no easy way to solve this issue. I think we should wait for Dynamo team's reply to your [github issue](https://github.com/DynamoDS/Dynamo/issues/6454) unless @ksobon knows some magical workarounds.

**Comment by SamDehghani** [comment]
Hi Lexico,
I made some changes to Konrad's node (Colored Surface Display) and was succesfully able to show results in Revit. I sent the modified node to Konrad to be reviewed. As soon as I get his comments I will send the workflow to Hydra on Gighub.
Sam

**Comment by mostaphaRoudsari** [comment]
Check [these examples](http://hydrashare.github.io/hydra/?keywords=samDehghanibake). Thanks @SamDehghani!
