### ISSUE TITLE
Dynamo 1.0.0

### ISSUE THREAD

**Issue by josols** [ladybug-analysis-tools/ladybug-dynamo#11]
Got errorno2 when testing in Dynamo 1.0.0 for Revit. Guessing it has something to do with dynamo being installed in new folder called Dynamo for Revit?

**Comment by mostaphaRoudsari** [comment]
Hi @josols, Thanks for reporting! I think you're right. I was still using an older release of Dynamo 1.0 which has the same folder structure. Let me check and get back to you soon. Cheers.

**Comment by mostaphaRoudsari** [comment]
@josols I did the first pass tonight and uploaded a new version but it won't fully solve the problem. I will work on it tomorrow and will update this issue once I have a working version.

**Comment by mostaphaRoudsari** [comment]
@josols try ladybug 0.0.8. It should work fine both under Revit or for stand-alone dynamo.

I have one extra fix for gencumsky before closing this issue.

**Comment by josols** [comment]
Now that's quick issue management! :) I'll try later on.

**Comment by 3sk0r** [comment]
@mostaphaRoudsari thanks!

**Comment by mostaphaRoudsari** [comment]
Just pushed 0.0.9 which solve the issue with radiation analysis too. Thanks again for reporting.
