### ISSUE TITLE
Ladybug 0.9 in #DynamoBIM 1.0.1 returning extra dates/vectors from analysis period

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-analysis-tools/ladybug-dynamo#12]
![](https://pbs.twimg.com/media/CinWpdSVEAA0CCc.jpg)
Read more [here](https://twitter.com/ParametricMnky/status/732352744640520192).

Reported by @ParametricMonkey! Thanks.

**Comment by mostaphaRoudsari** [comment]
@ParametricMonkey sorry for the delay on this. I started a series of performance enhancements that https://github.com/ladybug-analysis-tools/ladybug/commit/fbd7e48f9f3500295b54934bbfb0f491b1e2da09 enhancements that also addresses this issue.

PS: With the next release we will have a [radiance based sunlight hours analysis](https://github.com/ladybug-analysis-tools/honeybeex/issues/11#issuecomment-214799705) which is quite fast. I'm waiting for the new release of Radiance to send you a prototype to test. [There is a bug](https://unmethours.com/question/17201/rcontrib-misses-one-of-the-modifiers-if-number-of-modifiers-between-240-420/) in the current release which will be fixed in the next coming release. That should make a long-time dream come true.

**Comment by ParametricMonkey** [comment]
@mostaphaRoudsari so does this mean its updated or are you waiting until the next release?

**Comment by mostaphaRoudsari** [comment]
@ParametricMonkey back to AnalysisPeriod I haven't updated the package but I will do in the next two days and will close this issue. Sunlighthours will be out with the next major release in June but I can send you a prototype to test.

**Comment by Lexiko** [comment]
hi @mostaphaRoudsari i would be very interested in testing the sunlighthours prototype too if you like

**Comment by mostaphaRoudsari** [comment]
Hi @Lexiko! Great! I will share the link here after the new release of Radiance is out.

@rpg777 do you think that we will have a new release for Radiance any time soon?

**Comment by rpg777** [comment]
@mostaphaRoudsari yes, sorry it's been so long in coming. I will try to get those put together tomorrow.

**Comment by mostaphaRoudsari** [comment]
Hi @rpg777! Thanks for the quick reply. Anytime during this week will be great for me. So many thanks.

**Comment by rpg777** [comment]
No problem @mostaphaRoudsari, your payment will be to show me what you've been up to. This stuff looks cool.

**Comment by mostaphaRoudsari** [comment]
@rpg777 you got this. @sariths and I will [remotely] present all the new radiance related stuff during the radiance workshop. We haven't submitted our abstract but we will do soon.

**Comment by rpg777** [comment]
Win64 package available here, so far: https://github.com/NREL/Radiance/releases/tag/5.0.a.11
We'd love if you could grab this up and test it out @mostaphaRoudsari

**Comment by mostaphaRoudsari** [comment]
@rpg777 thanks! Just ran a couple of tests. The previous bug is fixed! :tada: Some of the points are still missing 1 or 2 modifiers out of +2700 suns. I need to take a closer look and see if I can find a pattern but this is different form the [previous issue](https://unmethours.com/question/17201/rcontrib-misses-one-of-the-modifiers-if-number-of-modifiers-between-240-420/). Thanks :)

![image](https://cloud.githubusercontent.com/assets/2915573/15520584/1ab174ae-21d5-11e6-91c8-691ce68f2afd.png)

**Comment by mostaphaRoudsari** [comment]
This is finally solved! Download version 0.1.1
![image](https://cloud.githubusercontent.com/assets/2915573/15769611/b1a44e20-292a-11e6-8652-ddd932f34880.png)

**Comment by ParametricMonkey** [comment]
@mostaphaRoudsari It still has extra dates, it has just moved to the end. In your image you have it going to 15:00, but the dates outputted are 15:45.

**Comment by mostaphaRoudsari** [comment]
@ParametricMonkey thanks for pointing this out. That was a different mistake at my end. It's fixed now. All of this issues is happening because the underlying calculation is based on minutes and I keep the inputs as month, day and hour. I hope this time it's fixed and fixed!

![image](https://cloud.githubusercontent.com/assets/2915573/15878470/2fa6b8fa-2ce9-11e6-8d03-d41555c17ec6.png)

I will push a new ladybug to package manager soon and update this issue.

**Comment by mostaphaRoudsari** [comment]
This is fixed!
