### ISSUE TITLE
Generate Sky Matrix not working?

### ISSUE THREAD

**Issue by josols** [ladybug-analysis-tools/ladybug-dynamo#13]
When I try the generate sky matrix I recieve an error: You need to calculate the matrix... If you see this within Dynamo try to rewire or something like that. Tried that but can't make it to work. Any suggestions?
![image](https://cloud.githubusercontent.com/assets/7080648/15481948/72003388-212d-11e6-8457-852aabc02794.png)

**Comment by mostaphaRoudsari** [comment]
Hi @josols, This is a known bug. It happens because Dynamo doesn't wait for the calculation the first time that you generate the sky matrix. The solution is to run it again and it will import the results that are already generated under the installation folder. Let me know if it does solve the issue.

**Comment by josols** [comment]
Thanks, I did try that. I even rewired as specified, but couldn't get it to work unfortunatey.

**Comment by mostaphaRoudsari** [comment]
@josols there is a white space in your directory path that Radiance doesn't like at all. Can you try a different folder with no white space? I thought that I fix this in the new release but looks like it still doesn't work on your machine. Sorry! :|

**Comment by josols** [comment]
hmm, I tried renaming the directory and choosing a different one with no whitespace. Still nothing I'm afraid. Also checked my version 0.0.9

**Comment by mostaphaRoudsari** [comment]
@josols let's see if you can generate the results manually on your machine. If you check the workingDir there should be a folder with the name of your weather file. (e.g. workingDir\Tampa_International_Ap). Inside the folder there are 4 files. Two of them are `.mtx` files and should be between 7-14 MB.

![image](https://cloud.githubusercontent.com/assets/2915573/15521307/0bc9bd30-21d9-11e6-8c14-39677254608b.png)

If the files are not generated correctly please open the batch file. Remove `@echo off` and add `Pause` as a new line to the end of the file and run it. We should be able to see the error.

![image](https://cloud.githubusercontent.com/assets/2915573/15521421/af4b5252-21d9-11e6-958f-83a185498be6.png)

If they are generated correctly then you just need to make dynamo re-run the script. If you're using the manuall mode you need to disconnect one of the inputs. Run the script. Connect it back and re-run it.

This is a solvable problem. Thank you for reporting and I'm sure that we will get it fixed soon. Cheers!

**Comment by mostaphaRoudsari** [comment]
@josols the new version `0.1.1` should fix this issue. Let me know if you still have issues.
