### ISSUE TITLE
Sunlighthours analysis test points

### ISSUE THREAD

**Issue by ParametricMonkey** [ladybug-analysis-tools/ladybug-dynamo#18]
Hi Mostapha

This is more of a wish list than a bug. When running a sunlight hour analysis in grasshopper the input (_geometry) is either a brep, mesh or surface. In Dynamo however the input is points (_testPoints). To generate these points I can use the 'generate test points' node which accepts surfaces and a UV division. The limitation I see is as follows:
- The UV subdivide doesn't include perimeter points and so the results are skewed.
- The UV subdivisions are not consistent. In GH I can specify the _gridSize. Ideally we want to control the resolution so for example, 500x500m mesh faces. Mesh setting in GH adresses this issue as does ladybug.
- Once I have run the analysis and filter out the complying points (>2hrs), then it is difficult to create a surface from those points. The 'MeshToolKit' doesn't have a Delaunay mesh or mesh from points or similar. It is much easier to filter existing mesh faces than trying to rebuild them from points.

So I guess my wish is for the Dynamo components to function more like the Grasshopper ones. Is there a reason as to why the methodology changed? 

Also, do you have any suggestions on how a heat map can be displayed within Revit. Dynamo has the element.OverrideColorInView node but I don't believe it is possible to apply a gradient colour to an element. i would need to create a bunch of smaller dummy geometry (like adaptive components) and color them individually. Do you have any better solutions? Essentially what i am trying to do is 'bake' the results into the Revit model once Dynamo is finished for future reference.

**Comment by Lexiko** [comment]
Hey Paul,

I was trying to achieve the same a few months ago before seeing your presentation at RTCAUS.
I was trying to use the FaceAnalysisDisplay node to represent the results, which wasn't working very well.
[http://dynamobim.org/forums/topic/face-analysis-display-by-view-face-points-and-values-node-bug/](url)
@ksobon has made a node which can achieve the result though.
![archi_lab method](https://cloud.githubusercontent.com/assets/18419461/16438922/dd6a3048-3df6-11e6-9a90-74947a80ad5a.png)
![revit_archilab_method](https://cloud.githubusercontent.com/assets/18419461/16438939/0301a840-3df7-11e6-8ce6-5e562ec7ff81.PNG)
Analysis views don't seem to "stick" in Revit but you could export the view to an image for record.
What do you think?

**Comment by ParametricMonkey** [comment]
Hi Alexis. As for the visualisation, it may work. Can you post a higher resolution pic. The graph isn't legible.

**Comment by Lexiko** [comment]
oops.
![archi_lab method2](https://cloud.githubusercontent.com/assets/18419461/16439711/62748566-3dfe-11e6-8884-384bf559203c.png)

[surface_test2.zip](https://github.com/ladybug-analysis-tools/ladybug-dynamo/files/338501/surface_test2.zip)
The top part is just generating some test points and random values.
I've included the definition file as well

**Comment by Lexiko** [comment]
Just a heads up Paul. I just remembered struggling to get this to work. "Units Names" and "Units Multipliers" inputs need to be lists.
![image](https://cloud.githubusercontent.com/assets/18419461/16439931/69230d18-3e00-11e6-9964-7386742af1ff.png)

**Comment by mostaphaRoudsari** [comment]
Hi Paul,

The reason to change geometry input to test points is to unify the interface between ladybug and honeybee and also make the process more flexible.

I agree with all your points for _Generate Test Points_ node. There are several limitations. I can add #16 and much more (e.g you can't calculate the area for each test point accurately. It will fail for trimmed faces, etc.).

The reason that it's different in Dynamo is because Dynamo doesn't have a proper meshing toolkit. I was hoping that it will be available at some point soon but it doesn't seem to happen.

I'm very cautious about doing any heavy geometrical calculation in Dynamo as [I didn't have a great experience so far](#8) but I think the solution for now is to write an algorithm that subdivide the surface and then use the center points for the analysis.

Back to the visualization @Lexiko has already answered your question. Also see this https://github.com/ladybug-analysis-tools/ladybug-dynamo/issues/10#issuecomment-211433268. There is an open issue on github and hopefully will be addressed at some point.

@alfarok back to our discussion about mesh in Dynamo this is one of the examples that we need quad mesh (or at least full control on mesh parameters so we can generate grid mesh) to generate test points and then the ability to color the mesh based on the results.

cc: @kronz

**Comment by ParametricMonkey** [comment]
OK. So I've had some time to digest all the information. Thanks for all the help. There seems to be lot of discussions already around the topic. Some observations/thoughts:
- The ladybug analysis is very slow. It is taking about 1 min to run for very minimal geometry (4 or 5 rooms). Is this because it is using surfaces instead or meshes? Is there a workable solution at the moment or are we reliant on improvements to dynamo first? I would like to run on much large models but I doubt it will be able to handle it.
- I've never used Revit's analysis display settings. How does Revit store this information? Is appears as though its inbuilt somehow as opposed to shared parameters. I'm keen to find out more. Presumably if we can get the Ladybug results to be visible using this technique then there is no need to create any dummy geometry within the Revit model. Now would there be a requirement for a quad mesh? But I don't enough how data is stored and if it can be easily extracted at a latter date.
- I tried 2 methods to visualise the results:
1. The OFTB Face Analysis Display method returned multiple outputs. However, unlike previous posts in other discussions, I don't see anything in Revit nor Dynamo. I understand this methodology has limitation in that the view is being refreshed at each iteration but I should see at least something.
2. I also tested the Archi-Lab method as suggested above but just got nulls. @ksobon Any ideas as to why this would fail?  

![solar](https://cloud.githubusercontent.com/assets/10913639/16551652/03add074-41fe-11e6-83ba-c9a4a4402e01.png)

[160704_Ladybug.zip](https://github.com/ladybug-analysis-tools/ladybug-dynamo/files/345663/160704_Ladybug.zip)

**Comment by Lexiko** [comment]
![image](https://cloud.githubusercontent.com/assets/18419461/16557782/1a089558-4225-11e6-80b8-5b1fb5a32749.png)
![image](https://cloud.githubusercontent.com/assets/18419461/16557805/39169094-4225-11e6-910a-c569d170e5a0.png)
You need to take your dynamo surfaces and  Import instance by geometries, remap test UV points to their domain. Plug those surfaces and uv points into the Archi-lab node and you're cooking with gas!

**Comment by ksobon** [comment]
@ParametricMonkey 

To answer your questions - those that @Lexiko didn't yet - I want to add this: 
- @mostaphaRoudsari can probably explain this more, but anything that has to do with Geometry in Dynamo is nosebleed slow and not very reliable. Meshes or surfaces, I am sorry but they are just a pain.
- Revit's Analysis Display Framework is stored with the model as a "display style" for a view. You can turn on the analysis display style for a given 3d view and save that setting. It's pretty good, but for surface display you need to import a surface to map that analysis to. Again, for some unknown to me reason Revit uses colored surfaces rather than meshes to display this - unless it doesn't and it somehow meshes the surfaces under the hood. I don't know much about that last part. Either way, you use the surface UVs to assign colors to specific locations on surface.

**Comment by mostaphaRoudsari** [comment]
A quick update.
1. The radiance-based method (aka. honeybee) will solve the issue. It takes a couple of seconds to run the analysis for a couple of rooms.
   ![image](https://cloud.githubusercontent.com/assets/2915573/16607837/9abbe5f8-4313-11e6-987b-8d0f41069886.png)
2. I made good progress on creating grid based on size similar to Grasshopper component.
   ![image](https://cloud.githubusercontent.com/assets/2915573/16607793/42353998-4313-11e6-8661-c2b9dafc4fab.png)

My plan is to push both of them to package manager at some point tomorrow. Will keep you posted.

**Comment by mostaphaRoudsari** [comment]
@ParametricMonkey, @Lexiko if you download the latest **ladybug** and **honeybee** from Dynamo package manager then you can try [sunlighthours.txt](https://github.com/ladybug-analysis-tools/ladybug-dynamo/files/350964/sunlighthours.txt) file that should address all the concerns about ladybug in this issue.

There are two new nodes that generate test points based on grid size. It also outputs UVs for test points which I assume will be useful for taking the results to Revit.

**Color Surfaces** node from Ladybug is now replaced with **Generate Colors**. You can take the colors and connect them to Display.ByGeometry.

I haven't tested _Rooms to HBZones_ with curtain walls so it may not work but you can just create honeybee surfaces out of Dynamo surfaces and use them instead. The workflow of Rooms to HBZones is much more cleaner though.

**_Finally, and this is important, you need to install [Radiance 5.0.a.11](https://github.com/NREL/Radiance/releases/tag/5.0.a.11). There has been [two bug fixes in radiance rcontrib](https://github.com/ladybug-analysis-tools/honeybeex/issues/11#issuecomment-229367057) which are critical to get accurate results for sunlight hours analysis.**_

Let me know if you have any issues.

![image](https://cloud.githubusercontent.com/assets/2915573/16635197/4b72ee06-439f-11e6-9583-f69bcf26f819.png)

**Comment by Lexiko** [comment]
Great! Looking forward to trying it out

**Comment by ParametricMonkey** [comment]
Thanks guys. I need a bit of time to go through all of this. I'll let you know how I get on.

**Comment by Lexiko** [comment]
Hi @mostaphaRoudsari , I'm having a couple of issues:
1) The "Rooms to HBZones" node fails when wall common to two rooms has a window in it
![error](https://cloud.githubusercontent.com/assets/18419461/16711867/2646637a-46b4-11e6-97a4-f37c64b41432.JPG)
![common_wall](https://cloud.githubusercontent.com/assets/18419461/16711872/94e977b8-46b4-11e6-9b68-39df34975656.JPG)

2) The results don't seem to reflect the fact there is a roof above
![separate_walls](https://cloud.githubusercontent.com/assets/18419461/16711869/3d605e76-46b4-11e6-9ca8-2b5684731ae6.JPG)

**Comment by mostaphaRoudsari** [comment]
Hi @lexiko! Thanks for reporting this. Can you share your model with me? I can give it a try today.

**Comment by Lexiko** [comment]
Hi @mostaphaRoudsari, I've included my Dynamo definition and Revit file.
[HERE](https://www.dropbox.com/s/ubjvwxgq1luvy19/AK_HB.zip?dl=0)
for some reason i can't drag my zip file into here :package:

**Comment by Lexiko** [comment]
Hi @mostaphaRoudsari I'm having trouble dropping the zip file in here. I've uploaded to dropbox [here](https://www.dropbox.com/s/ubjvwxgq1luvy19/AK_HB.zip?dl=0)

**Comment by mostaphaRoudsari** [comment]
Thanks @Lexiko! I will give it a try in a couple of hours.

**Comment by mostaphaRoudsari** [comment]
I opened two new issues with proper names. I'm going to close this one!

**Comment by ParametricMonkey** [comment]
@mostaphaRoudsari - When you say we should use Radiance 5.0.a.11, is that for Grasshopper as well as Dynamo? In which case, this needs to be updated: https://github.com/mostaphaRoudsari/ladybug/blob/master/resources/Installation_Instructions.md

Does this mean that all my scripts with 5.0.a.6 were all inaccurate?

**Comment by mostaphaRoudsari** [comment]
@ParametricMonkey all your analysis is fine. That's only the case for radiance-based sunlighthours which is currently only available in Honeybee for Dynamo. In Ladybug for Grasshopper the component uses Grasshopper for ray-tracing.

**Comment by schaggar16** [comment]
@Lexiko and @ParametricMonkey would you mind sharing how you managed to map the sunlight hours to the surface and into Revit. I am trying to do the same thing but for Lux levels.
