### ISSUE TITLE
RoomToZones: The results don't seem to reflect the fact there is a roof above

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-analysis-tools/ladybug-dynamo#20]
Reported [here](https://github.com/ladybug-analysis-tools/ladybug-dynamo/issues/18#issuecomment-231572072).

![](https://cloud.githubusercontent.com/assets/18419461/16711869/3d605e76-46b4-11e6-9ca8-2b5684731ae6.JPG)

@Lexiko I think this is a result of having Volume computations set to Area only in Revit. If that's the case then I need to add an extra check and raise an error for the user to change it. We can change it automatically but that might not be _what revit and revit users want!_

**Comment by mostaphaRoudsari** [comment]
I still don't know how to fix this but it happens because elementsData.GetBoundaryFaceInfo(face) returns an empty list for roof face in this model.

![image](https://cloud.githubusercontent.com/assets/2915573/16714663/273bba80-4698-11e6-9c9e-0d8f92001059.png)

**Comment by mostaphaRoudsari** [comment]
@Lexiko I checked the model and you're using offset to create the upper level and also create the room. Because of that Revit doesn't assign a corresponding boundary information for the top face of the room and that's why it returns an empty list. I recreated without offset and it works as expected. I can add an exception to raise if there is a case similar to this case. What are your thoughts on this?

**Comment by mostaphaRoudsari** [comment]
I made the code more forgiving for this case. Seems to be a common practice to create rooms similar to this model. @Lexiko the latest version should have all the issues that you have found fixed. Version 0.0.6.

**Comment by Lexiko** [comment]
hI @mostaphaRoudsari , yes i think that's a good idea. I thought about it and there are cases where, for example, there may be a split level or double height space where the room would have to be adjusted after placement. fixing this was definitely worthwhile, making the workflow more robust.
