### ISSUE TITLE
Benchmarking import epw node in Dynamo1.2 vs Dynamo and Grasshopper

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-analysis-tools/ladybug-dynamo#21]
I did run the Import Epw component/node in Dynamo1.2, Dynamo1 and Grasshopper for 10 times and here is the results. I used the sandbox version to exclude the _Revit effect_ from the comparisons.

| Program | python script execution time | total time (including assigning the outputs) | memory usage |
| --- | --- | --- | --- |
| Grasshopper | 2.55 s | 2.6 s | 210 MB |
| Dynamo 1 | 3.24 | **25.27 s** | 746 MB |
| Dynamo 1.2 | 3.36 | 6.23 s | 500 MB |

The quick conclusion is that the main time is spent in Dynamo to assign the outputs after running the code. There has been major improvments on that (from 25 to 6 seconds) but it's still around 3 times slower than Grasshopper.

Dynamo's python node is still using a lot of memory! Around 2.5 times more than Grasshopper. I also should add that I'm not using the new Grasshopper component which has some major performance enhancements. The memory numbers should be much lower than this.

The code takes 2 seconds to run from command-line in python.

**Comment by mdengusiak** [comment]
Hi Mostapha, I move also to Dynamo and I agree that Dynamo is much slower. Another issue is when you create/delete some element in Revit you can not run script second time. You need to close and open Dynamo again to clean some internal memory. There is still big task for Dynamo team to solve...

**Comment by mostaphaRoudsari** [comment]
Hi Michal, Thank you for adding your comment. Do you see a similar pattern in ZT nodes? That can make a huge difference if it's not only a problem with Python nodes but a problem with the Dynamo nodes in general? I think the development team will take it more seriously if this is a problem with Dynamo ZT nodes, otherwise, there is not that much passion on the Dynamo team to improve the performance of the Python node! :|

**Comment by mdengusiak** [comment]
I completely agree. I  would  definitely say that is problem with  Dynamo .  Grasshopper is definitely much faster, responsive and flexible. Improving Dynamo performance especially Python nodes should very high priority especially if we are planning to use this environment to do all similar task. At the moment is not as reliable as GH and crushing a lot. Also we need to close and open after runs etc,... but Dynamo should give us more opportunity than GH.
