### ISSUE TITLE
Ladybug Error / Honeybee Suface - SunStudy not creating color

### ISSUE THREAD

**Issue by sburg5000** [ladybug-analysis-tools/ladybug-dynamo#22]
I am receiving an ERROR: 'HBSuface' object has no attributes 'Points Parameter' I am trying to create a sun study with color on some parametric panels I created using a lofted surface and the native dynamo panel node. I am using Ladybug to generate the sun path and using ladybug's color nodes. I only get one color and only a 1/4 of the surface is getting color.
[10192016 805 AM - Screen Clipping.pdf](https://github.com/ladybug-analysis-tools/ladybug-dynamo/files/539070/10192016.805.AM.-.Screen.Clipping.pdf)

**Comment by mostaphaRoudsari** [comment]
This should be fixed in the new version. Check the new example  files in version `0.1.4`. You can download it from the package manager.
