### ISSUE TITLE
02_genTestPts.dyn not create color surface

### ISSUE THREAD

**Issue by gitgreencoder** [ladybug-analysis-tools/ladybug-dynamo#24]
The color Surface node returns error and color is not generated. Error: 'float' object has no attr. I am using REVIT 2016 and LB 0.1.3

**Comment by mostaphaRoudsari** [comment]
@gitgreencoder which version of Dynamo are you using?

**Comment by gitgreencoder** [comment]
1.2.0.

**Comment by mostaphaRoudsari** [comment]
@gitgreencoder try the new version `0.1.4`

![image](https://cloud.githubusercontent.com/assets/2915573/20250154/402dab22-a9d8-11e6-9bf1-3008aca6d5a7.png)
