### ISSUE TITLE
warning  - Generate Color Node

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-analysis-tools/ladybug-dynamo#26]
Hi,

I am struggling to get Generate Color node working,
seems that can not accept current structure,
Any idea how to fix it?

![image](https://cloud.githubusercontent.com/assets/14005893/25580361/4e2e5616-2e78-11e7-9548-32aa033bf28d.png)

**Comment by mostaphaRoudsari** [comment]
@mdengusiak you're using the node wrong. It takes `values` and `legend parameters` and then you should use Dynamo's Display nodes to color the surfaces. Check the  updated example files for an example.
