### ISSUE TITLE
RAM maxes out

### ISSUE THREAD

**Issue by schaggar16** [ladybug-analysis-tools/ladybug-dynamo#27]
When i run analysis for solar radiation i find that my RAM gets fully used up. If if i reduce the analysis points. 
This sometimes results in my machine crashing out which means i lose the results. 
Any solution to this?

**Comment by mostaphaRoudsari** [comment]
Yes. The solution is to use Honeybee and not Ladybug for radiation analysis. I'm removing radiation and sunlight hours from Ladybug as you can do both with honeybee in Dynamo. It doesn't seem that DynamoBIM geometry library will be improved at any point soon as you have probably seen it here: https://github.com/ladybug-tools/ladybug-dynamo/issues/8

![screenshot 4](https://cloud.githubusercontent.com/assets/2915573/26531869/e0584f80-43c0-11e7-8794-e8ebda2c2d8b.png)

**Comment by schaggar16** [comment]
@mostaphaRoudsari when i change the type to radiation i get a message that i should be using a climate based sky. i have tried both the sky nodes included as part of Honeybee but get same error. 
Could you provide an example of a radiation analysis using honeybee?

**Comment by mostaphaRoudsari** [comment]
Yes! Will do. Give me some time and I will get back to you here. It's not your fault. I noticed that we haven't added cumulative sky to honeybee.

**Comment by schaggar16** [comment]
@mostaphaRoudsari - sorry to pester but is there a time frame for the implementation of the cumulative sky to honeybee plus?

**Comment by mostaphaRoudsari** [comment]
@schaggar16! Thanks for keeping the pressure on! 😉  I just posted an update [here](https://github.com/ladybug-tools/ladybug-dynamo/issues/30#issuecomment-313456110). We need to make sure it goes hand in hand with the rest of the project, otherwise adding a single node should not take this long.

**Comment by schaggar16** [comment]
@mostaphaRoudsari glad i can help haha. and great stuff with the development off this - a real asset. looking forward to put the first release through it paces for you :)

**Comment by mostaphaRoudsari** [comment]
Resolved via https://github.com/ladybug-tools/honeybee-dynamo/commit/65e7b7d06e719f5b0a0a8c1834397bbccc12f7c7

Next release of Honeybee supports hourly, annual and cumulative radiation analysis.
