### ISSUE TITLE
Rooms to HBZones failled

### ISSUE THREAD

**Issue by denivaldopereira** [ladybug-analysis-tools/ladybug-dynamo#28]
Hi Mostapha! 
I am new member arround here, and first of all congratulate you for the LadyBug projetct. It's amazing!!!! I was using Ladybug and Honey Bee in grasshopper without not problems, but nowadays I am trying to use it in dynamo and I have a problem in the Rooms to HBZone. It doesn't working well. I got a print screen of what is going on there... 

Thank you very much! 

![ladybug](https://cloud.githubusercontent.com/assets/15792004/26653778/a0628bae-462a-11e7-81b5-c5594259f844.PNG)

**Comment by mostaphaRoudsari** [comment]
Hi @denivaldopereira, Thank you for the kind comments. Rooms to HBZones is not the most stable node. If you have checked the example files for Honeybee you probably have seen this comment:

![image](https://cloud.githubusercontent.com/assets/2915573/26691179/30f48826-46ca-11e7-9744-3c04c0824883.png)

Unfortunately Revit API doesn't provide the necessary support for getting the geometry of room which we need and this component is expected to break frequently. Saying that, is it possible for you to share your Revit model? I will take a look to see if I can fix the bug.

Meanwhile you can use Dynamo's select objects nodes to bring the geometries to Dynamo and set up the analysis. Is won't be as clean as using a single node but at least it will work.

Also there are some missing nodes from honeybee for Dynamo. I suggest to wait a couple of more weeks and I hope it will be shorter than that before you try honeybee for dynamo for everyday use.

**Comment by mostaphaRoudsari** [comment]
I'm closing this issue in favor of https://github.com/ladybug-tools/honeybee-dynamo/issues/61

Feel free to open an new issue under honeybee-dynamo repository and share your file.
