### ISSUE TITLE
ERROR: Minute must be in 0..59

### ISSUE THREAD

**Issue by KimberleyR** [ladybug-analysis-tools/ladybug-dynamo#29]
Hi there. Not too sure what is going wrong with my script that I have written. I have followed the tutorial guidelines (on youtube) but have been unsuccessful in the generation of drawing a sun path in dynamo, and the tutorial that brings it all together due to this error. The error has remained with it being 'minute must be in 0...59 >: (7/21@7:60) (m/d@h:m) 

Regards

**Comment by mostaphaRoudsari** [comment]
@KimberleyR someone else also reported this issue but I can't recreate it. Can you share your file with me?

**Comment by KimberleyR** [comment]
Hi there, 





Here is the error file. 



regards, 


Kimberley 


 


On Jun 06, 2017, at 04:51 PM, Mostapha Sadeghipour Roudsari <notifications@github.com> wrote:






@KimberleyR someone else also reported this issue but I can't recreate it. Can you share your file with me?

**Comment by mostaphaRoudsari** [comment]
@KimberleyR you need to attach the file on GitHub. You can't send it directly via email.

**Comment by KimberleyR** [comment]
My apologies. Will do so now. On 7/06/2017 11:59 AM, Mostapha Sadeghipour Roudsari <notifications@github.com> wrote:@KimberleyR you need to attach the file on GitHub. You can't send it directly via email.

**Comment by KimberleyR** [comment]
Hi, It wont let me attach the Dynamo file directly into this link, and dynamo wont let me convert it to a file that is accepted for upload

**Comment by Lexiko** [comment]
zip it or change the extension to .txt in windows explorer

**Comment by KimberleyR** [comment]
[sunlighthoursAnalysis.Error.zip](https://github.com/ladybug-tools/ladybug-dynamo/files/1056799/sunlighthoursAnalysis.Error.zip)

Hi, Thanks for that :)

**Comment by mostaphaRoudsari** [comment]
Hi @KimberleyR! Thanks for sharing. I could recreate the error and it's fixed now. I just pushed the updated version to package manager (0.1.7).

![image](https://user-images.githubusercontent.com/2915573/26887284-97f90d76-4b75-11e7-8bbc-2e68874174d9.png)
