### ISSUE TITLE
Peak solar radiation

### ISSUE THREAD

**Issue by teabaker** [ladybug-analysis-tools/ladybug-dynamo#30]
Hi!

I'm trying to find the peak solar radiation on windows, so that I can peform a solar heat gains analysis.

I'm running a Ladybug solar radiation analysis, but can only seem to get the total radiation over the analysis period.

![2017-06-21 13-41-51](https://user-images.githubusercontent.com/25978191/27382478-797fc930-5687-11e7-883e-62636d77030e.png)

Is there anyway to manipulate the inputs so that I can find the solar radiation for each hour in the analysis period? I tried to chop the HOYs into lists of 1, but this only produced an error in the FilterSkyMatrix node.

Thanks!

Nick

**Comment by mostaphaRoudsari** [comment]
Hi @teabaker, I'm sorry that all my answers recently ends up in using honeybee and then honeybee is not fully released to help you with what you need. Once we address [this issue](https://github.com/ladybug-tools/honeybee/issues/135) you will have hourly annual results by default which you can use to find the max / min and much more like setting up sensors and dynamic blinds. You can read more [here](https://github.com/ladybug-tools/honeybee/issues/105#issuecomment-306648184).

![dynamic_blinds_0](https://user-images.githubusercontent.com/2915573/26856662-2435620e-4af3-11e7-9654-d84cd18910e3.png)

![dynamic_blinds_1](https://user-images.githubusercontent.com/2915573/26856667-2d1a8908-4af3-11e7-84f8-cf6b36ba71f3.png)

**Comment by teabaker** [comment]
Ok, thanks for the quick response!

Do you have a rough idea of how long it will take to make this improvement?

A few days/weeks/months?

:)

**Comment by mostaphaRoudsari** [comment]
I would say a couple of weeks to a month! I have branched out from the master branch to make an overhaul to both ladybug and honeybee and [have already removed sunlight hours and radiation analysis from ladybug](https://github.com/ladybug-tools/ladybug/commit/95bcaeda543fa27a1f646d01e49c77ff93c9c9ab). Once the honeybee development branch is ready and merged back it should take us a week or two for testing and then we will release it to the package manager.

**Comment by mostaphaRoudsari** [comment]
Just an update here that you can hopefully test this before mid July. First release is the most challenging one as everything is up in the air. @sariths and I will have a talk tomorrow to discuss this in details.

**Comment by mostaphaRoudsari** [comment]
The nodes are added via https://github.com/ladybug-tools/honeybee-dynamo/commit/65e7b7d06e719f5b0a0a8c1834397bbccc12f7c7
