### ISSUE TITLE
Changing timestep into numeric number instead of integer number

### ISSUE THREAD

**Issue by najmehdokhanchi** [ladybug-analysis-tools/ladybug-dynamo#31]
Hello Mostapha ,
I want to create a sun path for a specific hour of a day for example the hour of 12:34 .
Could you please tell me how can I set non integer number for hoursOfYear in Analysis Period node? 
Best regards,
Najmeh

**Comment by mostaphaRoudsari** [comment]
Hi @najmehdokhanchi,

12:34 is 12 + 34 / 60 = 12.56667

you can use a code block for this calculation.

![image](https://user-images.githubusercontent.com/2915573/28279105-6db49872-6aed-11e7-8a06-97de0721a6ee.png)

**Comment by najmehdokhanchi** [comment]
Hello Mostapha ,
Thank you very much for your help.
Best regards,
Najmeh
