### ISSUE TITLE
radiance analysis without test grid

### ISSUE THREAD

**Issue by JeroenBg** [ladybug-analysis-tools/ladybug-dynamo#35]
Hi Mostapha,

I'm trying to create a radiance analysis on a big wavy train station roof surface. This is easy to do in Grasshopper, as the radiance analysis node 'projects' an analysis grid onto the roof surface. But my company preferences Dynamo instead.  In Dynamo I need to define a border for 'generate testpoints by grind size', which isn't accepted when its a irregular shape (both on the X and Y axis), so it seems. Is this inherent to ladybug in Dynamo, is there a workaround or am I missing something obvious here (new to this stuff)? 

thanks in advance for your time

**Comment by mostaphaRoudsari** [comment]
Hi @JeroenBg,

You can use any other Dynamo node to generate the points for irregular surfaces. Have you tried to work with evaluate surface node? For your case it sounds like the meshing nodes can also be helpful.

What honeybee needs for the analysis is a list of points (center points) with their directions (normal vector). Once you get the results you can visualize it with the same workflow.

PS: This is an issue for [honeybee-dynamo](https://github.com/ladybug-tools/ladybug-dynamo/issues/35)!

**Comment by JeroenBg** [comment]
[dynfile.zip](https://github.com/ladybug-tools/ladybug-dynamo/files/1416033/dynfile.zip)
hi @mostaphaRoudsari,

Thanks for your reply! I tried that but then the Cumulative Value node shows a single value for all points (if I understand it correctly). I thing I am doing something wrong, I've included the project in the zipfile. Also I don't see how this would work with shading from buildings in environment, which is the reason i'm running this analysis in the first place.

Could you confirm whether it is even possible doing a radiance analysis of a roof surface (watt/m2) with honeybee in dynamo with environment?
And what exactly does a honeybee surface do if the analysis is based on a grid of points?
And if I want the colors to display on the roof surface, I need to cut up the surface in equal amount of meshes as there are points in the grid right?

sorry for all the questions and time!! Thanks very much.

p.s. can i move this tread to honeybee-dynamo?

![capture](https://user-images.githubusercontent.com/32036556/32021183-f4a278f2-b9d2-11e7-9dfa-cfebc02ac880.png)

**Comment by mostaphaRoudsari** [comment]
@JeroenBg, Sorry that I missed this one here! Is this still an issue or did you figure it out?
I think the right place for this question is the forum. More people can help and it doesn't get lost.
http://discourse.ladybug.tools/t/welcome-to-ladybug-tools-forum/8

**Comment by JeroenBg** [comment]
Hi Mostapha,

No problem, I figured it out myself! Can't remember how exactly but it worked in the end. Thanks for your help end this awesome tool.

**Comment by mostaphaRoudsari** [comment]
Thank you for the update! Happy that you solved the issue. We really need to capture some tutorials for Honeybee in Dynamo. There is not much out there to get people started.
