### ISSUE TITLE
ladybug-dynamo 1.9 and 1.5

### ISSUE THREAD

**Issue by ahmad7sn** [ladybug-analysis-tools/ladybug-dynamo#36]
Hello,
I have installed ladybug for dynamo latest version 1.9 and it seems that it missing some nodes when i open the sample files Mostapha provided specially sunlight hours analysis file. When i open the file on 1.5 version it works normally. Is it a common problem or is there something i can do to fix this issue?

I do use Grasshopper and ladybug plugin is working fine, but the issue is that I'm developing a new workflow for our office that we will use Revit in the design phase so I'm testing it on Dynamo to reduce time switching between software as Dynamo compatible with Revit.

![dynamo](https://user-images.githubusercontent.com/35929593/35563442-5433dc38-05bf-11e8-993e-fae4a2f9a096.jpg)

**Comment by mostaphaRoudsari** [comment]
Hi @ahmad7sn, Sunlighthours is part of honeybee. Did you also updated your honeybee installation?

**Comment by ahmad7sn** [comment]
@mostaphaRoudsari, Yes, Honeybee version is 0.1.7. Have you changed the nodes names?

**Comment by mostaphaRoudsari** [comment]
@ahmad7sn, no I haven't. We just released new versions of Ladybug and Honeybee and I updated the example files that comes with the installation and the ones on Hydra. Can you try this file and let me know if it works.
http://hydrashare.github.io/hydra/viewer?owner=mostaphaRoudsari&fork=hydra_1&id=Sunlighthours_Ladybug_Dynamo&slide=0&scale=1&offset=0,0

**Comment by ahmad7sn** [comment]
@mostaphaRoudsari, Yup, it is working! thanks for you help.

**Comment by mostaphaRoudsari** [comment]
Great to hear! 🐞🍂!

**Comment by OrtizJ3** [comment]
Greetings! I'm having the same issue with the missing Sunlighthours Analysis node. I'm using Revit 2020. Are there any updates planned?
