### ISSUE TITLE
Hourly values radiance analysis are zero

### ISSUE THREAD

**Issue by rozaslera** [ladybug-analysis-tools/ladybug-dynamo#38]
Hi, I am trying to perform a day light analysis.. the hourly values are zero. I have tried to connect different epw files for locations.  Radiance is installed in c:/Radiance. 

Sorry maybe the issue is a stupid mistake but i am new to ladybug tools.

Thanks

Emanuele
![capture](https://user-images.githubusercontent.com/37893601/41297121-bef84b1e-6e5e-11e8-8036-1c8848d1cb24.png)

**Comment by mostaphaRoudsari** [comment]
I'm closing this issue as it has been so long from when this issue is posted.
We just updated the installation package for Ladybug and Honeybee. Please update your installation and run the script. If that didn't solve the issue please post it to the forum (discourse.ladybug.tools)
